inherit_gem:
  rubocop-coreyja:
    - config/coreyja.yml

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'vendor/**/*'

Metrics/ClassLength:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

RSpec/MultipleExpectations:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/cli/**/*.rb'

RSpec/ExampleLength:
  Max: 10
