inherit_gem:
  rubocop-coreyja:
    - config/default.yml

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4

RSpec/MultipleExpectations:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/cli/**/*.rb'

RSpec/ExampleLength:
  Max: 10
