version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/ruby:2.3.4

    steps:
      - checkout

      ## Bundler
      # Restore Cache
      - restore_cache:
          keys:
            - gem-cache-{{ checksum "sleet.gemspec" }}
      # Install
      - run: bundle check || bundle install --path vendor/bundle
      # Store Cache
      - save_cache:
          key: gem-cache-{{ checksum "sleet.gemspec" }}
          paths:
            - vendor/bundle

      - type: shell
        command: |
          bundle exec rubocop \
            --config .rubocop.yml \
            -r $(bundle show rubocop-junit-formatter)/lib/rubocop/formatter/junit_formatter.rb \
            --format RuboCop::Formatter::JUnitFormatter \
            --out /tmp/test-results/rubocop.xml \
            --format progress \
            --force-exclusion \
            $(bundle exec rubocop --list-target-files | circleci tests split --split-by=filesize --show-counts)

      # Run rspec in parallel
      - type: shell
        command: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings --show-counts)

      # Save artifacts
      - type: store_test_results
        path: /tmp/test-results

      - store_artifacts:
          path: spec/.rspec_example_statuses

